import Head from "next/head";
import Projects from "../components/Projects";
import About from "../components/About";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Skills from "../components/Skills";
import Contact from "../components/Contact";
export default function Home() {
  return (
    <div className="bg-fixed bg-no-repeat bg-cover bg-center bg-[url('../public/assets/1.jpg')]">
      <Head>
        <title>Hari Charan K | Front-end Developer and Artist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
